export {default as Hero} from './Hero' 
export {default as Navbar} from './Navbar'
export {default as Cocktails} from './Cocktails'
export {default as About} from './About'
export {default as Art} from './Art'
export {default as Menu} from './Menu'
export {default as Contact } from './Contact'